'use client';
import { useEffect, useRef } from 'react';
import { X, ArrowRight, FileText } from 'lucide-react';
import type { Clause } from '@/types/contract';
export default function ClauseDetails({ clause, onClose }: { clause: Clause; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const dialog = ref.current; dialog?.showModal(); const previous = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { dialog?.close(); document.body.style.overflow = previous; }; }, []);
  return <dialog ref={ref} className="detail-panel" aria-labelledby="detail-title" onCancel={onClose} onClick={e => { if (e.target === ref.current) onClose(); }}><div className="detail-inner"><div className="panel-top"><span className="section-label">CLAUSE REVIEW</span><button className="icon-button" aria-label="Close clause details" onClick={onClose}><X size={20}/></button></div><h2 id="detail-title">{clause.name}</h2><div className="detail-meta"><span className={`badge ${clause.status}`}>{clause.status}</span><span className="confidence">Matching confidence: <span className="capitalize">{clause.confidence}</span></span></div>
    {clause.confidence === 'low' && <p className="review-note">This clause should be reviewed manually because the corresponding provision could not be matched confidently.</p>}
    <section><h3>Company position</h3><p>{clause.companyPosition || 'No equivalent provision in the company template.'}</p>{clause.companySection && <small>{clause.companySection}</small>}</section><section><h3>Client position</h3><p>{clause.clientPosition || 'No equivalent provision identified.'}</p>{clause.clientSection && <small>{clause.clientSection}</small>}</section><section><h3>What changed</h3><p>{clause.difference}</p></section>{clause.suggestedAction && <section className="suggestion"><h3><ArrowRight size={15}/> Suggested action</h3><p>{clause.suggestedAction}</p></section>}<section className="source-section"><h3>Source text</h3><p className="source-help">Verify the comparison against the original wording.</p>{[{ label: 'Company Template', text: clause.companySourceText }, { label: 'Client Contract', text: clause.clientSourceText }].map(source => <details key={source.label}><summary><FileText size={15}/>{source.label}</summary><blockquote>{source.text || 'No equivalent provision identified.'}</blockquote></details>)}</section><p className="legal-note">Operational review support, not legal advice.</p></div></dialog>;
}
